{% set name = "expectexception" %}
{% set version = "0.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ExpectException-{{ version }}.tar.gz
  sha256: e51ef71e85721d97c44aa2bb6d4ed128900ba10341a373d8b40487b9314a74e9

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - IPython
    - python >={{ python_min }}

test:
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/thedataincubator/expectexception
  summary: Jupyter magic for exceptions
  license: BSD-3-Clause
  # Check with upstream to have them package license file
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
